export enum ERROR_TYPE {
    ACCESS_TOKEN = 'AccessTokenError',
    AUTH_FAILURE = 'AuthFailureError',
    BAD_REQUEST = 'BadRequestError',
    BAD_TOKEN = 'BadTokenError',
    CONFLICT = 'ConflictError',
    FORBIDDEN = 'ForbiddenError',
    FILE_EXISTS = 'FileExistsError',
    FILE_NOT_EXISTS = 'FileNotExistsError',
    INTERNAL = 'InternalError',
    NOT_FOUND = 'NotFoundError',
    NOT_ACCEPTABLE = 'NotAcceptableError',
    NO_DATA = 'NoDataError',
    NO_ENTRY = 'NoEntryError',
    NOTIFICATION_ERROR = 'NotificationError',
    RESOURCE_EXISTS = 'ResourceExistsError',
    RESOURCE_NOT_EXISTS = 'ResourceDoesNotExistsError',
    TOKEN_EXPIRED = 'TokenExpiredError',
    TRANSACTION_ERROR = 'TransactionError',
    UNAUTHORIZED = 'UnauthorizedError',
    UNPROCESSABLE_ENTITY = 'UnprocessableEntityError',
}
